### ISSUE TITLE
Nodes Are Not visible in Install missing Custom Nodes

### ISSUE THREAD

**Issue by mneyanmels** [logtd/ComfyUI-HunyuanLoom#13]
![Image](https://github.com/user-attachments/assets/744d12f8-3e16-44e1-8d90-4eafad96754a)

Alswo whan i am trying Install using Pip it's not visibal as well

**Comment by TooAiArt** [comment]
It happens to me too

**Comment by LukeG89** [comment]
@mneyanmels @TooAiArt In the Manager, you have to change the channel from `default` to `dev`

**Comment by TooAiArt** [comment]
> [@mneyanmels](https://github.com/mneyanmels) [@TooAiArt](https://github.com/TooAiArt) In the Manager, you have to change the channel from `default` to `dev`

I have tried it and if they appear in missing custom nodes, but once installed I always get import failed, I have given try fix and the same, I have uninstalled and reinstalled it and also import failed.

I have also tried it via git and the same

**Comment by mneyanmels** [comment]
Problem is fixed from my side, i just updated comfyui using update.bat file
, not from user interface inside comfy

**Comment by LukeG89** [comment]
> I have tried it and if they appear in missing custom nodes, but once installed I always get import failed, I have given try fix and the same, I have uninstalled and reinstalled it and also import failed.
> 
> I have also tried it via git and the same

@TooAiArt If I remember correctly, I had the same problem because I was missing diffusers. Can you confirm?
This custom node has no requirements.txt, so it doesn't install any dependency and the "Try fix" won't do anything.

Post the startup logs in case using the update.bat didn't fix the issue

**Comment by ls080824** [comment]
pip install diffusers

Install and reboot the server and de nodes are back.

**Comment by MeteKanat** [comment]
ı change security level and work for me 
https://github.com/comfyanonymous/ComfyUI_TensorRT/issues/6#issuecomment-2365284241

**Comment by loliq** [comment]
Hello, I met the same problem, any solutions?
